add colorized output and symbols in terminal
Neufund/smart-contract-watch pull request #56
Opened 2017-12-12 14:59 UTC by cedricwalter

add colored terminal and symbols :)

![2017-12-12 15_57_37-smart-contract-watch-cedric c__users_cedric_ideaprojects_smart-contract-watch-c](https://user-images.githubusercontent.com/763491/33891181-74c394b0-df55-11e7-89fc-7eac327dac51.png)

2018-01-10 11:50 UTC, Moejoe90 requested changes
Thanks for this new addition, it will make looking into the terminal more pleasant. 

why are you checking if it is windows and changing the character based on that is it a known encoding problem?
1- eslint errors 
2- Merge conflicts
3- some comments

2018-01-10 11:50 UTC, Moejoe90 commented on src/command.js
> +const defaultColors = '1'; // No color 1 Ansi, 2 Chalk
default should be null

2018-01-10 11:50 UTC, Moejoe90 commented on src/command.js
> +      .option('-c,--colors [n]', 'use color 1 for ansi, 2 for chalk, any other for none', handelInputValues('COLORS', watchConfig.colors, defaultColors))
let's make it three values 1,2,empty any other value should raise an exception

2018-01-10 11:50 UTC, Moejoe90 commented on src/output/index.js
> +      throw new Error(`${type} output module is undefined`);
nice catch

2018-01-10 11:50 UTC, Moejoe90 commented on src/output/terminalFormat.js
> +    // blue: styleFactory('blue'),
remove comment

2018-01-10 11:50 UTC, Moejoe90 commented on src/output/terminalFormat.js
> +// Dep modules
use import instead of require

2018-01-10 11:50 UTC, Moejoe90 commented on src/output/terminalFormat.js
> +  function styleFactory(color) {
change to arrow function

2018-01-25 13:09 UTC, cedricwalter commented
feedback implemented and PR up to date with master

2018-02-06 15:57 UTC, Moejoe90 requested changes
Please make sure Travis builds your PR successfully before submitting for review.

2026-01-13 14:43 UTC, closed without merging